## try-catch
ここでは、try-catchついて説明していきます。

### 目次
* [try-catchとは](#sec1)
* [try-catchの使用例](#sec2)
* [RuntimeException](#sec3)
* [Error](#sec4)

### <a name="sec1"></a>try-catchとは
Exceptionに対する例外処理の1つとしてtry-catchがあります。  
try-catchの構文は以下になります。

```sh
try {
	// 例外が発生する可能性がある文;
	・・・
	} catch (<例外クラス><変数名>) {
		// 例外が発生したときに行う処理
	}
}
```

catchブロックが実行されるのは、対応するtryブロックの内部で発生した例外をキャッチする場合だけです。
catchブロックは発生する可能性のある例外1つ1つに対して記述する必要があります。

### <a name="sec1"></a>try-catchの使用例
以下はtry-catchの使用例になります。

```java
public class Sample6_1 {
	public static void main(String[] args) {
		int x = 15;
		int y = 0;
		try {
			System.out.println("x / y :" + x / y);
			System.out.println("x * y :" + x * y);
		} catch(ArithmeticException ae) {
			System.out.println("ArithmeticException" + ae);
		}
		System.out.println("x - y :" + (x - y));
	}
}
```

今回の例では、RuntimeExceptionクラスを継承したArithmeticExceptionクラスなので、例外処理を記述していなくてもコンパイルエラーにはなりませんが、実行時にエラーとなります。

